### ISSUE TITLE
issue when decrypting some libs

### ISSUE THREAD

**Issue by Super-brawl-team** [Mimi8298/Supercell.ArxanUnprotector#2]
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'address')
   at Supercell.ArxanUnprotector.iOS64Library.Take(Int32 address, Int32 length) in C:\Users\Gene\Source\Repos\ArxanUnprotector\Supercell.ArxanUnprotector\iOS64Library.cs:line 87
   at Supercell.ArxanUnprotector.Strings.EncryptedStringKey.get_Content() in C:\Users\Gene\Source\Repos\ArxanUnprotector\Supercell.ArxanUnprotector\Strings\EncryptedStringKey.cs:line 20
   at Supercell.ArxanUnprotector.Actions.DecryptStringsAction.Execute(Library original, Library modified, String output) in C:\Users\Gene\Source\Repos\ArxanUnprotector\Supercell.ArxanUnprotector\Actions\DecryptStringsAction.cs:line 30
   at Program.<Main>$(String[] args) in C:\Users\Gene\Source\Repos\ArxanUnprotector\Supercell.ArxanUnprotector\Program.cs:line 45

**Comment by astralsc** [comment]
bro i got that same problem but it happend for android

C:\Users\cromo\Documents\Supercell.ArxanUnprotector-main\Supercell.ArxanUnprotector\bin\Debug\net7.0>Supercell.ArxanUnprotector.exe -a update-crc -i "C:\Users\cromo\Documents\APK.Tool.GUI.v3.3.1.6 (1)\Files\com.supercell.clashofclans_10.134.4-965_minAPI15(armeabi-v7a,x86)(nodpi)_apkmirror.com\lib\armeabi-v7a\libg.so" -m "C:\Users\cromo\Documents\APK.Tool.GUI.v3.3.1.6 (1)\Files\libgmodified.so" -o "C:\Users\cromo\Documents\APK.Tool.GUI.v3.3.1.6 (1)\Files\libgmodified.so"
Unhandled exception. System.NotSupportedException: Could not find String table.
   at Supercell.ArxanUnprotector.Strings.Providers.ArmStringEncryptionService.FindStringTable() in C:\Users\cromo\Documents\Supercell.ArxanUnprotector-main\Supercell.ArxanUnprotector\Strings\Providers\ArmStringEncryptionService.cs:line 65
   at Supercell.ArxanUnprotector.Library.get_EncryptedStringRangeTable() in C:\Users\cromo\Documents\Supercell.ArxanUnprotector-main\Supercell.ArxanUnprotector\Library.cs:line 90
   at Supercell.ArxanUnprotector.Library.EncryptStringsImpl() in C:\Users\cromo\Documents\Supercell.ArxanUnprotector-main\Supercell.ArxanUnprotector\Library.cs:line 171
   at Supercell.ArxanUnprotector.Library.DecryptStrings() in C:\Users\cromo\Documents\Supercell.ArxanUnprotector-main\Supercell.ArxanUnprotector\Library.cs:line 150
   at Supercell.ArxanUnprotector.Actions.UpdateChecksumsAction.Execute(Library original, Library modified, String output) in C:\Users\cromo\Documents\Supercell.ArxanUnprotector-main\Supercell.ArxanUnprotector\Actions\UpdateChecksumsAction.cs:line 18
   at Program.<Main>$(String[] args) in C:\Users\cromo\Documents\Supercell.ArxanUnprotector-main\Supercell.ArxanUnprotector\Program.cs:line 45
